- name: Install wazuh
  hosts: all
  tasks:
    - name: Download wazuh
      ansible.builtin.get_url:
        url: https://packages.wazuh.com/4.7/wazuh-install.sh
        dest: /tmp/wazuh-install.sh
        mode: '+x'
    - name: Install wazuh
      shell: /bin/bash /tmp/wazuh-install.sh -a
