#cloud-config
package_update: true
package_upgrade: true

hostname: main
fqdn: main.leito.tech

packages:
  - git
  - zsh

# ATTENTION: Paste your ssh public key herre
users:
  - name: leito
    primary_group: leito
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/zsh
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsl2rYv+wy/rrLfk0Q10bvUuvGwtOG6oejMqR9iwQqHZ3eQ3mUwYstrMxrspOK2Ik+NcwZkO+zkTJAlq1rbKTFQhXj9yp6d6WKJkenSfa2MVmmsFxRg/gqGQzOmHiEp2ITfU3zviqNlG68blRUQotKVCLynHgERqw2XODms4mfzda0T8OI7vGp+PK4HcAjL44+ecYHYhAgxpTLBab25u2q5pWlS6OLuQFcHJS4E9U1Nz3UCEbm8lLmMAVtISTvF4FCfK51EFzpagiMt9naK/Z78wRdYQ4ytOX4qzFv6ZmuvEPdUsgXFmG65RPzkkpU0cdDS4PonPcHSyvERrEJqLgX
