#cloud-config
package_update: true
package_upgrade: true

packages:
  - git
  - go
ansible:
  install_method: distro
  pull:
    url: "https://github.com/leitosama/infra.git"
    playbook_name: interact/playbook.yaml