- name: Setup interact.leito.tech
  hosts: '{{ pb_hosts | default("all") }}'
  tasks:
    - name: Rolling update
      community.general.pacman:
        upgrade: true

    - name: Install pexpect
      community.general.pacman:
        name:
          - python-pexpect

    - name: Download blackarch
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/BlackArch/blackarch-site/master/strap.sh
        checksum: sha1:https://raw.githubusercontent.com/BlackArch/blackarch-site/master/checksums/strap
        dest: /tmp/blackarch.sh
        mode: '+x'

    - name: Install blackarch
      ansible.builtin.expect:
        command: /tmp/blackarch.sh
        creates: /etc/pacman.d/blackarch-mirrorlist
        responses:
          '[Y/n]': Y

    - name: Install packages
      community.general.pacman:
        name:
          - go
          - metasploit
        state: present

    - name: Check that pdtm installed
      ansible.builtin.stat:
        path: /usr/local/bin/pdtm
      register: pdtm_installed

    - name: Install pdtm
      environment:
        GOBIN: /usr/local/bin/
      ansible.builtin.command: go install -v github.com/projectdiscovery/pdtm/cmd/pdtm@latest
      register: pdtm_install
      changed_when: 'pdtm_install.rc == 0'
      when: 'pdtm_installed.stat.exists == 0'

    - name: Install ProjectDiscovery Projects
      ansible.builtin.command: /usr/local/bin/pdtm -ia -ip
      register: pd_installed
      changed_when: 'pd_installed.stderr == "interactsh-server: already installed"'

    - name: Download Sliver C2 Installer
      ansible.builtin.get_url:
        url: https://sliver.sh/install
        dest: /tmp/sliver.sh
        mode: '+x'

    - name: Install Sliver C2
      ansible.builtin.expect:
        command: /tmp/sliver.sh
        creates: /usr/local/bin/sliver
        responses:
          '[Y/n]': Y

    - name: Remove pexpect
      community.general.pacman:
        name:
          - python-pexpect
        state: absent
