- name: Setup interact.leito.tech
  hosts: '{{ pb_hosts | default("all") }}'
  tasks:
    - name: Rolling update
      community.general.pacman:
        upgrade: true

    - name: Download blackarch
      ansible.builtin.get_url:
        url: https://blackarch.org/strap.sh
        checksum: sha1:3f121404fd02216a053f7394b8dab67f105228e3
        dest: /tmp/blackarch.sh
        mode: '+x'

    - name: Install blackarch
      ansible.builtin.expect:
        command: /tmp/blackarch.sh
        creates: /etc/pacman.d/blackarch-mirrorlist
        responses:
          '[Y/n]': Y

    - name: Update keyrings
      community.general.pacman:
        name:
          - blackarch-keyring
          - archlinux-keyring
        update_cache: true

    - name: Install packages
      community.general.pacman:
        name:
          - go
          - metasploit
        state: present

    - name: Download Sliver C2 Installer
      ansible.builtin.get_url:
        url: https://sliver.sh/install
        dest: /tmp/sliver.sh
        mode: '+x'

    - name: Install Sliver C2
      ansible.builtin.script: /tmp/sliver.sh

    - name: Check that pdtm installed
      ansible.builtin.stat:
        path: /usr/local/bin/pdtm
      register: pdtm_installed

    - name: Install pdtm
      environment:
        GOBIN: /usr/local/bin/
      ansible.builtin.command: go install -v github.com/projectdiscovery/pdtm/cmd/pdtm@latest
      changed_when: true
      when: pdtm_installed.stat.exists

    - name: Install ProjectDiscovery Projects
      ansible.builtin.command: /usr/local/bin/pdtm -ia -ip
      register: pd_installed
      changed_when: 'pd_installed.rc == 0'
