- name: Setup interact.leito.tech
  hosts: all
  vars:
    blackarch_site_commit: "1cf23dbe93fa9f85b586b8dda84d0320244f262b"
  tasks:
    - name: Install/upgrade archlinux-keyring before full update
      community.general.pacman:
        update_cache: true
        state: latest
        name:
          - archlinux-keyring

    - name: Rolling update
      community.general.pacman:
        upgrade: true

    - name: Install pexpect
      community.general.pacman:
        name:
          - python-pexpect

    - name: Download blackarch
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/BlackArch/blackarch-site/{{ blackarch_site_commit }}/strap.sh
        checksum: sha1:https://raw.githubusercontent.com/BlackArch/blackarch-site/{{ blackarch_site_commit }}/checksums/strap
        dest: /tmp/blackarch.sh
        mode: '+x'

    - name: Install blackarch
      ansible.builtin.expect:
        command: /tmp/blackarch.sh
        creates: /etc/pacman.d/blackarch-mirrorlist
        responses:
          '[Y/n]': Y

    - name: Install packages
      community.general.pacman:
        name:
          - go
          - metasploit
          - httpie
          - gobuster
        state: present

    - name: Install pdtm
      environment:
        GOBIN: /usr/local/bin/
      ansible.builtin.command:
        cmd: go install -v github.com/projectdiscovery/pdtm/cmd/pdtm@latest
        creates: /usr/local/bin/pdtm

    - name: Install ProjectDiscovery Projects
      ansible.builtin.command: /usr/local/bin/pdtm -ia -ip
      register: pd_installed
      changed_when: 'pd_installed.stderr == "interactsh-server: already installed"'

    - name: Download Sliver C2 Installer
      ansible.builtin.uri:
        url: https://sliver.sh/install
        return_content: true
      register: sliver_installer

    - name: Install Sliver C2
      ansible.builtin.expect:
        command: "echo {{ sliver_installer.content }} | sh -s -- -y"
        creates: /usr/local/bin/sliver
        responses:
          '[Y/n]': Y

    - name: Remove pexpect
      community.general.pacman:
        name:
          - python-pexpect
        state: absent
