- name: Setup Outline
  become: true
  hosts: 3x-ui
  vars:
    version: '2.4.11'
    xui_user: 'leito'
    xui_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=10'|string) }}"
    xui_port: '13337'
    xui_webpath: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=10'|string) }}"
    xui_folder: "/usr/local/x-ui/"
  tasks:
    - name: Update and install packages
      ansible.builtin.package:
        name:
          - wget
          - curl
          - tar
          - "{{ 'timezone' if ansible_pkg_mgr == 'zypper' else 'tzdata' }}"
        state: present
        update_cache: true

    - name: Extract tar.gz
      ansible.builtin.unarchive:
        src: "https://github.com/MHSanaei/3x-ui/releases/download/v{{ version }}/x-ui-linux-amd64.tar.gz"
        remote_src: true
        dest: /usr/local/
        mode: '755'
        owner: 'root'
        group: 'root'

    - name: Install service
      ansible.builtin.command:
        creates: /etc/systemd/system/x-ui.service
        cmd: "cp {{ xui_folder }}/x-ui.service /etc/systemd/system/x-ui.service"

    - name: Get x-ui.sh
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/MHSanaei/3x-ui/main/x-ui.sh
        dest: /usr/bin/x-ui
        mode: '755'

    - name: Setup config
      ansible.builtin.shell:
        cmd: |
          {{ xui_folder }}/x-ui setting -username "{{ xui_user }}" -password "{{ xui_password }}" -port "{{ xui_port }}" -webBasePath "{{ xui_webpath }}" >/dev/null
          {{ xui_folder }}/x-ui setting -show
          touch {{ xui_folder }}/ansible-configured
        creates: "{{ xui_folder }}/ansible-configured"
      register: config

    - name: Print config
      ansible.builtin.debug:
        msg: "{{ config.stdout }}"

    - name: Enable and start service
      ansible.builtin.systemd_service:
        daemon_reload: true
        enabled: true
        name: x-ui
        state: started
