services:
  wg-easy:
    env_file: .env
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./.wg-easy:/etc/wireguard
    ports:
      - '51820:51820/udp'
      - '51821:51821/tcp'
    restart: unless-stopped
    image: weejewel/wg-easy

