#!/usr/bin/env python3
"""Build a PAC file from the slim geo text lists.

Everything matching the lists (geosite-*.txt / <geoip>.txt) goes DIRECT,
everything else goes through the proxy.

usage: geo2pac.py [-p "SOCKS5 127.0.0.1:9050"] [-o proxy.pac] DIR
"""
import argparse
import ipaddress
import re
import sys
from pathlib import Path


def parse_geosite(path):
    domain, full, keyword, regexp = set(), set(), [], []
    for line in path.read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        kind, _, rest = line.partition(":")
        if not rest:  # bare entry == domain
            kind, rest = "domain", kind
        value = rest.split(":", 1)[0].split()[0].lower()
        if kind == "domain":
            domain.add(value)
        elif kind == "full":
            full.add(value)
        elif kind == "keyword":
            keyword.append(value)
        elif kind == "regexp":
            regexp.append(rest.split(" @", 1)[0].strip())
    return domain, full, keyword, regexp


def parse_cidrs(path):
    nets = []
    for line in path.read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        net = ipaddress.ip_network(line, strict=False)
        if net.version == 4:  # PAC resolvers return IPv4 only
            nets.append(net)
    return nets


def merge_ranges(nets):
    ranges = sorted((int(n.network_address), int(n.broadcast_address)) for n in nets)
    merged = []
    for lo, hi in ranges:
        if merged and lo <= merged[-1][1] + 1:
            merged[-1][1] = max(merged[-1][1], hi)
        else:
            merged.append([lo, hi])
    return merged


def js_list(items):
    return "[" + ",".join(items) + "]"


def js_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


TEMPLATE = r"""// Generated by openwrt/geo2pac.py - do not edit by hand.
// DIRECT: geosite lists ({site_lists}) and geoip lists ({ip_lists}).
// Everything else: PROXY.
var PROXY = {proxy};
var DIRECT = "DIRECT";

var DOMAINS = {domains};   // domain: suffix match
var FULL = {full};         // full: exact match
var KEYWORDS = {keywords};
var REGEXPS = {regexps};
var RANGES = {ranges};     // flat sorted [lo0,hi0,lo1,hi1,...] of IPv4 as uint32

function ipToNum(ip) {{
  var p = ip.split(".");
  return ((+p[0]) * 16777216) + ((+p[1]) << 16) + ((+p[2]) << 8) + (+p[3]);
}}

function inRanges(n) {{
  var lo = 0, hi = (RANGES.length >> 1) - 1;
  while (lo <= hi) {{
    var mid = (lo + hi) >> 1;
    if (n < RANGES[mid * 2]) hi = mid - 1;
    else if (n > RANGES[mid * 2 + 1]) lo = mid + 1;
    else return true;
  }}
  return false;
}}

function domainMatch(host) {{
  if (FULL_SET.hasOwnProperty(host)) return true;
  var h = host;
  while (true) {{
    if (DOMAIN_SET.hasOwnProperty(h)) return true;
    var i = h.indexOf(".");
    if (i < 0) break;
    h = h.substring(i + 1);
  }}
  var k;
  for (k = 0; k < KEYWORDS.length; k++) if (host.indexOf(KEYWORDS[k]) >= 0) return true;
  for (k = 0; k < REGEXPS.length; k++) if (new RegExp(REGEXPS[k]).test(host)) return true;
  return false;
}}

var DOMAIN_SET = {{}}, FULL_SET = {{}};
(function () {{
  var i;
  for (i = 0; i < DOMAINS.length; i++) DOMAIN_SET[DOMAINS[i]] = 1;
  for (i = 0; i < FULL.length; i++) FULL_SET[FULL[i]] = 1;
}})();

function FindProxyForURL(url, host) {{
  host = host.toLowerCase();
  if (host.indexOf(":") >= 0) return DIRECT;               // IPv6 literal / loopback
  if (/^\d+\.\d+\.\d+\.\d+$/.test(host)) return inRanges(ipToNum(host)) ? DIRECT : PROXY;
  if (isPlainHostName(host) || domainMatch(host)) return DIRECT;
  var ip = dnsResolve(host);
  if (ip && /^\d+\.\d+\.\d+\.\d+$/.test(ip) && inRanges(ipToNum(ip))) return DIRECT;
  return PROXY;
}}
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("dir", type=Path, help="dir with geosite-*.txt and geoip *.txt")
    ap.add_argument("-p", "--proxy", default="SOCKS5 127.0.0.1:9050")
    ap.add_argument("-o", "--output", type=Path, default=Path("proxy.pac"))
    a = ap.parse_args()

    site_files = sorted(a.dir.glob("geosite-*.txt"))
    ip_files = sorted(f for f in a.dir.glob("*.txt") if not f.name.startswith("geosite-"))
    if not site_files or not ip_files:
        sys.exit("no geosite-*.txt / geoip *.txt files found in %s" % a.dir)

    domain, full, keyword, regexp = set(), set(), [], []
    for f in site_files:
        d, fl, k, r = parse_geosite(f)
        domain |= d
        full |= fl
        keyword += k
        regexp += r
    # drop exact entries already covered by a suffix rule
    def covered(h):
        parts = h.split(".")
        return any(".".join(parts[i:]) in domain for i in range(len(parts)))
    full = {h for h in full if not covered(h)}
    domain = {h for h in domain if not any(
        ".".join(h.split(".")[i:]) in domain for i in range(1, len(h.split("."))))}
    for r in regexp:
        re.compile(r)

    nets = [n for f in ip_files for n in parse_cidrs(f)]
    flat = [str(x) for lo, hi in merge_ranges(nets) for x in (lo, hi)]

    a.output.write_text(TEMPLATE.format(
        site_lists=", ".join(f.stem[len("geosite-"):] for f in site_files),
        ip_lists=", ".join(f.stem for f in ip_files),
        proxy=js_str(a.proxy),
        domains=js_list(js_str(x) for x in sorted(domain)),
        full=js_list(js_str(x) for x in sorted(full)),
        keywords=js_list(js_str(x) for x in sorted(set(keyword))),
        regexps=js_list(js_str(x) for x in sorted(set(regexp))),
        ranges=js_list(flat),
    ))
    print("%s: %d domains, %d full, %d keywords, %d regexps, %d ranges" % (
        a.output, len(domain), len(full), len(set(keyword)), len(set(regexp)), len(flat) // 2))


if __name__ == "__main__":
    main()
