- name: Setup dino.leito.tech
  hosts: all
  tasks:
    - name: Download velociraptor
      ansible.builtin.get_url:
        url: https://github.com/Velocidex/velociraptor/releases/download/v0.72/velociraptor-v0.72.1-linux-amd64-musl
        dest: ./velociraptor
        mode: '+x'

    - name: Templating veloconfig
      ansible.builtin.template:
        src: templates/veloconfig.json.j2
        dest: ./veloconfig.json
        mode: '0660'

    - name: Generate server config
      ansible.builtin.shell: ./velociraptor config generate --merge_file=./veloconfig.json > ./server.config.yaml
      args:
        creates: ./server.config.yaml

    - name: Generate debian server package
      ansible.builtin.shell: ./velociraptor -c ./server.config.yaml debian server --output /tmp/velociraptor_server.deb
      args:
        creates: /tmp/velociraptor_server.deb

    - name: Make clients directory
      ansible.builtin.file:
        path:  "{{  clients_path  }}"
        state: directory
        owner: velociraptor
        group: velociraptor
        mode: '0660'

    - name: Install Velociraptor debian package
      ansible.builtin.apt:
        deb: /tmp/velociraptor_server.deb

    - name: Generate client config
      ansible.builtin.shell: |
        ./velociraptor -c ./server.config.yaml config client > {{ clients_path }}/client.config.yaml
      args:
        creates: "{{ clients_path }}/client.config.yaml"

    - name: Generate debian client
      ansible.builtin.shell: |
        ./velociraptor -c {{ clients_path }}/client.config.yaml \
        debian client --output {{ clients_path }}/velociraptor_client.deb
      args:
        creates: "{{ clients_path }}/velociraptor_client.deb"

    - name: Generate rpm client
      ansible.builtin.shell: |
        ./velociraptor -c {{ clients_path }}/client.config.yaml \
        debian client --output {{ clients_path }}/velociraptor_client.rpm
      args:
        creates: "{{ clients_path }}/velociraptor_client.rpm"
