- name: Setup dino.leito.tech
  hosts: all
  tasks:
    - name: Download velociraptor
      ansible.builtin.get_url:
        url: https://github.com/Velocidex/velociraptor/releases/download/v0.72/velociraptor-v0.72.1-linux-amd64-musl
        dest: /tmp/velociraptor
        mode: '+x'

    - name: Templating veloconfig
      ansible.builtin.template:
        src: templates/veloconfig.json.j2
        dest: /tmp/veloconfig.json
        mode: '0660'

    - name: Generate server config
      ansible.builtin.shell: /tmp/velociraptor config generate --merge_file=/tmp/veloconfig.json > /tmp/server.config.yaml
      args:
        creates: /tmp/server.config.yaml

    - name: Generate debian server package
      ansible.builtin.shell: /tmp/velociraptor -c /tmp/server.config.yaml debian server --output /tmp/velociraptor_server.deb
      args:
        creates: /tmp/velociraptor_server.deb

    - name: Install Velociraptor debian package
      ansible.builtin.apt:
        deb: /tmp/velociraptor_server.deb

    - name: Install nginx
      ansible.builtin.apt:
        name: nginx

    - name: Configure nginx
      ansible.builtin.copy:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/sites-available/default
    
    - name: Restart nginx
      ansible.builtin.systemd_service:
        name: nginx
        state: started

    - name: Generate client config
      ansible.builtin.shell: |
        /tmp/velociraptor -c /tmp/server.config.yaml config client > /var/www/html/client.config.yaml
      args:
        creates: "/var/www/html/client.config.yaml"

    - name: Generate debian client
      ansible.builtin.shell: |
        /tmp/velociraptor -c /var/www/html/client.config.yaml \
        debian client --output /var/www/html/velociraptor_client.deb
      args:
        creates: "/var/www/html/velociraptor_client.deb"

    - name: Generate rpm client
      ansible.builtin.shell: |
        /tmp/velociraptor -c /var/www/html/client.config.yaml \
        debian client --output /var/www/html/velociraptor_client.rpm
      args:
        creates: "/var/www/html/velociraptor_client.rpm"

    - name: Fix perms for all files in /var/www/html/
      ansible.builtin.file:
        path: /var/www/html/
        recurse: true
        mode: '0755'
