---
  - name: Setup hostname 
    ansible.builtin.hostname:
      name: "{{ inventory_hostname }}"
  - name: Change /etc/hosts
    ansible.builtin.lineinfile:
      path: /etc/hosts
      line: "127.0.0.1 {{ inventory_hostname }}"
      state: present
      backup: true
  - name: Install git and zsh
    ansible.builtin.package:
      name:
        - git
        - zsh
      state: present
  - name: Add user
    ansible.builtin.user:
      name: "{{ user }}"
      state: present
      shell: /bin/zsh
  - name: Change sudo for user
    ansible.builtin.lineinfile:
      path: /etc/sudoers
      line: "{{ user }} ALL=(ALL) NOPASSWD: ALL"
      state: present
      validate: 'visudo -cf %s'
      backup: true
  - name: Fix ssh config
    ansible.builtin.blockinfile:
      path: /etc/ssh/sshd_config
      block: | 
       KexAlgorithms -ecdh-sha2-nistp*,diffie-hellman-group14-sha256
       HostKeyAlgorithms -ecdsa-sha2-nistp256
       MACs -umac-64-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
      backup: true 
  - name: Add ssh key
    ansible.posix.authorized_key:
      user: "{{ user }}"
      state: present
      key: "{{ ssh_key }}"
  - name: Set MOTD
    become: true
    ansible.builtin.copy:
      src: motd
      dest: /etc/motd
      mode: '0600'

