---
driver:
  name: docker
platforms:
  - name: instance
    image: archlinux:base-devel
    pre_build_image: false
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        ansible_user: root